### PR TITLE
12 Hour Clock Option

### PR DESCRIPTION
**Pull request by d4mation**
I grew up using a 12 hour clock and 24 hour clocks always take me a second to determine which hour it is.

This works with all the various clock-related options.

### CODE REVIEW

**Comment by Nanquitas** [comment]
Hi :)

It's indeed a good idea, thank you.
I see there's conflict with my last commit... :/

**Comment by d4mation** [comment]
Ah, shoot. You're right. I'll fix this up in a bit. I made this PR before you pushed that commit up.

**Comment by Nanquitas** [comment]
It's okay, it wasn't that bad actually, so I fixed it. :)

I'll test it and if everything works I'll do the release for v5. 
Thanks again. :)

**Comment by d4mation** [comment]
No problem! Thanks for taking care of the merge conflict!

**Pull request merged**
